ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x03D80E40>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x03D80E40>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x03D80E40>, trait: thresholds, old value: None, new value: inf 0.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.8 -10.0 0.3 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x03D80E40>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x03D80E40>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x03E7BB10>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_Nf:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_Nf:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B3632A0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B3632A0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B3632A0>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.8 -10.0 0.3 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B3632A0>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B3632A0>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x0B40E1B0>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_3v:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_3v:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B063FC0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B063FC0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B063FC0>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.8 -10.0 0.3 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B063FC0>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0B063FC0>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x0AA0B450>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_kQ:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_cQ:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_cQ:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_cQ:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.functions.GuessesToFit object at 0x0BA89FC0>, trait: run_fitting, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 358, in execute_fitting
    self.fitting.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\functions.py", line 381, in execute
    self.fit_E.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\fit.py", line 33, in execute
    full_output=True)
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\leastsqbound.py", line 273, in leastsqbound
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds
ERROR:traits:Exception occurred in traits notification handler for object: <alex.functions.GuessesToFit object at 0x0BA89FC0>, trait: run_fitting, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 358, in execute_fitting
    self.fitting.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\functions.py", line 381, in execute
    self.fit_E.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\fit.py", line 33, in execute
    full_output=True)
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\leastsqbound.py", line 273, in leastsqbound
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds
WARNING:enaml.session:Invalid object id sent to Session: o_kj:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_kj:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_kj:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_cj:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.functions.GuessesToFit object at 0x0BA89FC0>, trait: run_fitting, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 358, in execute_fitting
    self.fitting.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\functions.py", line 382, in execute
    self.fit_S.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\fit.py", line 33, in execute
    full_output=True)
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\leastsqbound.py", line 273, in leastsqbound
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds
ERROR:traits:Exception occurred in traits notification handler for object: <alex.functions.GuessesToFit object at 0x0BA89FC0>, trait: run_fitting, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 358, in execute_fitting
    self.fitting.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\functions.py", line 382, in execute
    self.fit_S.execute()
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\fit.py", line 33, in execute
    full_output=True)
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\leastsqbound.py", line 273, in leastsqbound
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds
WARNING:enaml.session:Invalid object id sent to Session: o_HS:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_HS:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0C452F60>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0C452F60>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0C452F60>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.699911606311 -10.0 0.362820055768 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0C452F60>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0C452F60>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x10D77C00>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_az:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_az:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10FA58A0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10FA58A0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10FA58A0>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.699911606311 -10.0 0.362820055768 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10FA58A0>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10FA58A0>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x0C5DB540>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_8p:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_8p:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10A804E0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10A804E0>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10A804E0>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.699911606311 -10.0 0.362820055768 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10A804E0>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10A804E0>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x03E7BA50>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_Ct:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_Ct:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0BDF1180>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0BDF1180>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0BDF1180>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.699911606311 -10.0 0.362820055768 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0BDF1180>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x0BDF1180>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x11A29F30>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_8G:changed
WARNING:enaml.session:Invalid object id sent to Session: o_8G:clicked
WARNING:enaml.session:Invalid object id sent to Session: o_8G:changed
WARNING:enaml.session:Invalid object id sent to Session: o_8G:clicked
WARNING:enaml.session:Invalid object id sent to Session: o_tG:changed
WARNING:enaml.session:Invalid object id sent to Session: o_tG:clicked
WARNING:enaml.session:Invalid object id sent to Session: o_tG:changed
WARNING:enaml.session:Invalid object id sent to Session: o_tG:clicked
WARNING:enaml.session:Invalid object id sent to Session: o_xi:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_xi:index_changed
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10AA8810>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 58, in update_binning
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10AA8810>, trait: plot_options, old value: None, new value: 1.0 0.0 1.0 0.0 [101, 101] False False
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 49, in update_range
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10AA8810>, trait: thresholds, old value: None, new value: inf 100.0 inf 0.0 10.0 1.0 -10.0 0.0 10.0 0.699911606311 -10.0 0.362820055768 inf 0.0 inf 250.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 68, in apply_thresholds
    self.data_container._apply_thresholds()
AttributeError: 'NoneType' object has no attribute '_apply_thresholds'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10AA8810>, trait: evss_layers, old value: None, new value: True False True True True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 98, in redraw_plot
    self.plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.controller.EvsSViewController object at 0x10AA8810>, trait: corr, old value: None, new value: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 136, in apply_corrections
    self.data_container.update()
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:traits:Exception occurred in traits notification handler for object: 0.0 False 0.0 0.0 1.0 0.0 0.0 0.0 1.0, trait: thorben_hack, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\mixins.py", line 111, in script_bg
    photons = self.data_manager.datasets[0].get_photons()
AttributeError: 'NoneType' object has no attribute 'datasets'
ERROR:traits:Exception occurred in traits notification handler for object: <alex.views.EvsSPlot object at 0x111C9DB0>, trait: rectangle, old value: None, new value: <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "C:\Documents and Settings\confocal\Desktop\ALEX-Suite-master\alex\controller.py", line 391, in add_guess_rect
    x1 = rect[0][0]
TypeError: '_Undefined' object does not support indexing
WARNING:enaml.session:Invalid object id sent to Session: o_6B:index_changed
WARNING:enaml.session:Invalid object id sent to Session: o_6B:index_changed
